import OpenAI from 'openai';
const client=new OpenAI({apiKey:process.env.OPENAI_API_KEY});
const json=async(prompt,images=[])=>{const content=[{type:'input_text',text:prompt},...images.map(url=>({type:'input_image',image_url:url,detail:'high'}))];const r=await client.responses.create({model:process.env.OPENAI_VISION_MODEL||'gpt-4.1',input:[{role:'user',content}],text:{format:{type:'json_object'}}});return JSON.parse(r.output_text)};
export default async function handler(req,res){if(req.method!=='POST')return res.status(405).json({error:'Method not allowed.'});if(!process.env.OPENAI_API_KEY)return res.status(500).json({error:'OPENAI_API_KEY is missing.'});try{const {action,context,profile,image,images,group,screenshots}=req.body||{};
if(action==='profile'){const p=await json(`You are PicPlanr creating an initial account understanding from onboarding details only. Use British English. Do not infer an industry, niche, service, audience, competitor strategy or brand personality that was not explicitly supplied. Context: ${JSON.stringify(context)}. Return JSON with summary string, voice_traits array of 4 strings, content_direction string, writing_rules string, confidence_note string, and needs_more_information boolean. The summary must describe only supplied facts. If information is incomplete, say so clearly. Do not use em dashes or American spelling.`);return res.json({profile:p})}
if(action==='audit'){const shotList=Array.isArray(screenshots)?screenshots.filter(x=>x&&x.dataUrl):[];const shotMeta=shotList.map(x=>({platform:x.platform}));const a=await json(`You are PicPlanr's Account Strength analyst. Score the account fairly from 0 to 100 using only the supplied onboarding details and any supplied profile screenshots. Context: ${JSON.stringify(context)}. Profile: ${JSON.stringify(profile||{})}. Supplied screenshot platforms: ${JSON.stringify(shotMeta)}. A typed handle alone is not evidence that you viewed a live page. When no screenshot is supplied, the score is provisional and must not exceed 65. When screenshots are supplied, inspect only what is visibly legible and do not invent follower counts, engagement, posting frequency, recent content or performance. Score these seven categories: Profile clarity, Visual consistency, Content balance, Trust and proof, Video readiness, Posting consistency, Conversion readiness. For categories that cannot be verified, give a cautious score and clearly say what is missing. Return JSON with overall_score integer, score_label string, hook_message string, score_basis string, confidence string, next_action string, breakdown array of exactly 7 objects with category, score integer and reason, plus strengths, improvements and actions, each an array of exactly 3 short practical strings. The overall score should broadly reflect the seven category scores. Use British English. Do not use em dashes, en dashes or American spelling.`,shotList.map(x=>x.dataUrl));return res.json({audit:a})}
if(action==='image'){const a=await json(`You are PicPlanr's evidence-only image examiner. Accuracy is more important than creativity. Analyse exactly one image. Account context is background only and must never override what is actually visible. Context: ${JSON.stringify(context)}. Voice profile: ${JSON.stringify(profile)}. Return JSON with: literal_summary (one neutral sentence describing only clearly visible content), confirmed_subjects array of objects with name and confidence (high/medium only), confirmed_setting string, confirmed_actions array, readable_text array containing only text that is genuinely legible, marketing_uses array of safe possible uses, grouping_keywords array, overall_confidence (high/medium/low), prohibited_inferences array, and unsuitable_for_caption boolean. Rules: do not infer an event type, relationship, pet-friendly policy, service, product, location, date, occasion, emotion, ownership or business capability unless directly visible or explicitly supplied in context. A visible dog proves only that a dog is visible; it does not prove the venue is pet-friendly. A wedding dress may suggest formal clothing but does not prove a wedding unless additional clear evidence exists. Never convert uncertain objects into specific items. If text is unclear, omit it.`,[image.dataUrl]);return res.json({analysis:a})}
if(action==='validate'){if(!group)return res.status(400).json({error:'Validation group is missing.'});const urls=(images||[]).map(x=>x.dataUrl);const evidence=(images||[]).map(x=>({image_id:x.image_id,analysis:x.analysis}));const v=await json(`You are PicPlanr's final accuracy auditor. Compare the proposed content group against the actual original images. Context: ${JSON.stringify(context)}. Voice profile: ${JSON.stringify(profile)}. Proposed group: ${JSON.stringify(group)}. Earlier evidence: ${JSON.stringify(evidence)}. Return JSON with group object containing: approved_for_display boolean, accuracy_status (checked or review), accuracy_notes array, title, format, objective, group_reason, schedule with day/time/reason, and captions array of exactly 3 objects using this exact structure:
    [{"label":"Natural","text":"caption text"},{"label":"Engagement","text":"caption text"},{"label":"Goal-led","text":"caption text"}].
    Every text value must be a non-empty string. 
Caption writing rules:
1. Do not describe the image sentence by sentence.
2. Do not begin with phrases such as "A closer look at", "This image shows", "Featuring", "Here we see" or "The photo captures".
3. Use the image only as context for a natural social post.
4. The Natural option should sound like something the client would casually post.
5. The Engagement option should ask one easy, relevant question.
6. The Goal-led option should connect naturally to the account goal without sounding like an advert.
7. Mention no more than one visible detail unless essential.
8. Keep each caption between 4 and 22 words.
9. Avoid generic artificial intelligence wording such as showcase, elevate, unforgettable, stunning, ambience, versatile, ideal setting, unique touch and perfect backdrop.
10. Use British English. Do not use em dashes or en dashes.
 Correct every unsupported claim. Never remove all caption text. If a proposed caption is inaccurate, rewrite it into a safe accurate caption rather than returning an empty value. The title, reason and captions must be true for every image in the group. Never infer pet-friendly policy from a visible dog. Never claim the client provides styling, planning, catering or another service unless explicitly stated in context. Never identify an object more specifically than the image supports. If the images do not form a coherent group, set approved_for_display=false. Captions must sound natural, must not be image descriptions, and must use only verified facts plus explicit account context. Write all user-facing copy in British English. Use spellings such as colour, organise, personalised and centre. Never use em dashes, en dashes or spaced hyphens in captions. Use commas, full stops or separate sentences instead.  Write all user-facing copy in British English. Use spellings such as colour, organise, personalised and centre. Never use em dashes, en dashes or spaced hyphens in captions. Use commas, full stops or separate sentences instead. `,urls);return res.json(v)}
if(action==='single_post'){if(!image?.dataUrl)return res.status(400).json({error:'Image is missing.'});const p=await json(`You are PicPlanr's conservative single-image post editor. This image must remain in the content plan because every uploaded image must be used exactly once. Analyse the original image directly. Context: ${JSON.stringify(context)}. Voice profile: ${JSON.stringify(profile||{})}. Earlier evidence: ${JSON.stringify(image.analysis||{})}. Return JSON with group object containing: title, format set to Single post, objective, group_reason, The title must be a short content angle, not a literal image description.  schedule with day, time and reason, accuracy_status set to checked or review, accuracy_notes array, and captions using this exact structure:
[{"label":"Natural","text":"caption text"},{"label":"Engagement","text":"caption text"},{"label":"Goal-led","text":"caption text"}].
Every text must be non-empty, natural British English and accurate to the visible image. 
Caption writing rules:
1. Do not describe the image sentence by sentence.
2. Do not begin with phrases such as "A closer look at", "This image shows", "Featuring", "Here we see" or "The photo captures".
3. Use the image only as context for a natural social post.
4. The Natural option should sound like something the client would casually post.
5. The Engagement option should ask one easy, relevant question.
6. The Goal-led option should connect naturally to the account goal without sounding like an advert.
7. Mention no more than one visible detail unless essential.
8. Keep each caption between 4 and 22 words.
9. Avoid generic artificial intelligence wording such as showcase, elevate, unforgettable, stunning, ambience, versatile, ideal setting, unique touch and perfect backdrop.
10. Use British English. Do not use em dashes or en dashes.
 Do not invent services, policies, offers, dates, people, relationships, events or locations. Do not use em dashes or American spelling.`,[image.dataUrl]);return res.json(p)}
if(action==='story_image'){if(!image?.dataUrl)return res.status(400).json({error:'Story image is missing.'});const s=await json(`You are PicPlanr's strict Instagram Story image editor. Analyse this one original portrait image directly. Accuracy is more important than creativity. Context: ${JSON.stringify(context)}. Voice profile: ${JSON.stringify(profile||{})}. Earlier evidence: ${JSON.stringify(image.analysis||{})}. First identify the single main visual subject. The Story title, description, frame instructions and all text options must focus on that main subject. Do not shift focus to background décor, venue features, services or policies unless they are clearly the main subject. Example rule: if a dog wearing formal clothing is the main subject, write about the dog and its outfit. Do not turn it into a venue décor, pet-friendly policy or event-planning Story. Never invent a name, event, relationship, service, offer, date, availability or customer action. Return JSON with story object containing: image_index, primary_subject, title, purpose, description, best_time, frames array of exactly 3 short instructions, and text_options using this exact structure:
[{"label":"Quick update","text":"short phrase"},{"label":"Engagement","text":"short question"},{"label":"Call to action","text":"short next step"}].
Every text value must be a non-empty string. Each option must be a short natural British English phrase, maximum 12 words. Quick update should state a simple visible truth. Engagement should ask a question directly related to the visible main subject. Call to action should use a safe generic action such as reply, react, follow or view more. Do not use em dashes, en dashes, American spelling or marketing clichés. If the image is ambiguous, use only the safest clearly visible main subject and still return three short, non-empty text options. Do not return an empty text_options array.`,[image.dataUrl]);return res.json(s)}
if(action==='stories'){const s=await json(`You are PicPlanr's Instagram Story strategist. Create practical Story updates only from the supplied portrait-image analyses. Stories are not feed captions. They should be short, current, conversational and useful for keeping customers or followers informed. Context: ${JSON.stringify(context)}. Voice profile: ${JSON.stringify(profile)}. Portrait image analyses: ${JSON.stringify(images)}. Create 1-8 Story ideas. Use each image at most once unless there are very few portrait images. Never invent facts, dates, offers, events, availability, products or outcomes. Use only details present in the image analysis and supplied account context. Each Story must return: image_index, title, purpose, description, best_time, frames array of exactly 3 short instructions, and text_options array of exactly 3 objects. The three text option labels must be Quick update, Engagement, and Call to action. Each text must be a short phrase suitable as an Instagram Story overlay, ideally under 12 words and never more than 18 words. Write all user-facing copy in British English. Use spellings such as colour, organise, personalised and centre. Never use em dashes, en dashes or spaced hyphens in captions. Use commas, full stops or separate sentences instead.  Quick update should keep customers informed. Engagement should ask a natural question. Call to action should give one simple next step. Return JSON object with stories array.`);return res.json(s)}
if(action==='group'){const g=await json(`You are PicPlanr's conservative content planner. Group images using the stable image_id values exactly as supplied. Context: ${JSON.stringify(context)}. Voice profile: ${JSON.stringify(profile)}. Evidence-only image analyses: ${JSON.stringify(images)}. Rules: use only confirmed evidence. Never use an image in more than one group. Never mix images just because they share a broad business category. Group only when subjects, setting, event, visual sequence or theme clearly match. Do not infer pet-friendly policies, event styling services, planning services, products, dates, relationships, occasions or capabilities unless explicitly supplied in context. Every supplied image_id must appear in exactly one group. Never omit an image. If an image does not match another, create a conservative Single post for it. Create 1-50 groups. For each group return: title, image_ids array using exact supplied IDs. The title must be a short content angle, not a literal image description.  format (Single post or Carousel), objective, group_reason, schedule with day, time and reason, and captions array of exactly 3 objects using this exact structure:
    [{"label":"Natural","text":"caption text"},{"label":"Engagement","text":"caption text"},{"label":"Goal-led","text":"caption text"}].
    Every text value must be a non-empty string. 
Caption writing rules:
1. Do not describe the image sentence by sentence.
2. Do not begin with phrases such as "A closer look at", "This image shows", "Featuring", "Here we see" or "The photo captures".
3. Use the image only as context for a natural social post.
4. The Natural option should sound like something the client would casually post.
5. The Engagement option should ask one easy, relevant question.
6. The Goal-led option should connect naturally to the account goal without sounding like an advert.
7. Mention no more than one visible detail unless essential.
8. Keep each caption between 4 and 22 words.
9. Avoid generic artificial intelligence wording such as showcase, elevate, unforgettable, stunning, ambience, versatile, ideal setting, unique touch and perfect backdrop.
10. Use British English. Do not use em dashes or en dashes.
 Captions must not list everything visible. Captions must not claim the business offers a service unless that service appears in context. Goal-led captions may use a generic action such as enquire, visit the website or follow, but must not invent offers or availability. Return JSON object with groups array.`);return res.json(g)}return res.status(400).json({error:'Unknown action.'})}catch(e){console.error(e);let m=e.message||'AI request failed.';if(e.status===401)m='The OpenAI API key is invalid.';if(e.status===429)m='The OpenAI account has reached a billing or rate limit.';return res.status(e.status&&e.status<600?e.status:500).json({error:m})}}
